spring.datasource.url=jdbc:postgresql://localhost:5432/quantumml
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

quantumml.app.jwtSecret=quantumMLSecretKeyThatIsVeryLongAndSecureEnoughForHS256Algorithm
quantumml.app.jwtExpirationMs=86400000

server.port=8080
